"""add_notification_history_table

Revision ID: b4e2c9a1f7d3
Revises: 8f8d07f5e0d6
Create Date: 2026-04-01 20:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4e2c9a1f7d3'
down_revision: Union[str, None] = '8f8d07f5e0d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False, comment='通知标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='通知内容'),
    sa.Column('channel', sa.String(length=50), nullable=False, comment='通知频道'),
    sa.Column('level', sa.Enum('INFO', 'WARNING', 'ERROR', 'CRITICAL', name='notificationlevel'), nullable=True, comment='通知级别'),
    sa.Column('is_read', sa.Boolean(), nullable=True, comment='是否已读'),
    sa.Column('recipients', sa.Text(), nullable=True, comment='收件人(JSON)'),
    sa.Column('data', sa.Text(), nullable=True, comment='附加数据(JSON)'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='通知历史记录表'
    )
    op.create_index(op.f('ix_notification_history_id'), 'notification_history', ['id'], unique=False)
    op.create_index(op.f('ix_notification_history_created_at'), 'notification_history', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_history_created_at'), table_name='notification_history')
    op.drop_index(op.f('ix_notification_history_id'), table_name='notification_history')
    op.drop_table('notification_history')
    # ### end Alembic commands ###
